use std::path::{Path, PathBuf};

use anyhow::{bail, Result};

const TEMPLATE: &str = r#"# Artemis Agent Profile
# Generated by `artemis new agent`

[agent]
name = "AGENT_NAME"
model = "sonnet"
skippable = false
tags = []

[system]
prompt = "You are a helpful assistant. Return JSON."

[tools]
enabled = ["read_file", "grep"]

[behavior]
behavior_type = "strict"
confidence_threshold = 0.7
max_retries = 2

[handoff]
# fallback = "next-agent"

# Define handoff rules — evaluated in order, first match wins.
# [[handoff.rules]]
# condition = { field = "confidence", op = ">", value = "0.5" }
# target = "next-agent"
#
# [[handoff.rules]]
# default = true
# target = null  # pipeline ends
"#;

pub fn run(name: String) -> Result<()> {
    let dir = agents_dir().join(&name);

    if dir.exists() {
        bail!(
            "Agent '{}' already exists at '{}'",
            name,
            dir.display()
        );
    }

    std::fs::create_dir_all(&dir)?;

    let template = TEMPLATE.replace("AGENT_NAME", &name);
    let toml_path = dir.join("agent.toml");
    std::fs::write(&toml_path, template)?;

    println!("Created agent '{}' at {}", name, dir.display());
    println!();
    println!("  {}", toml_path.display());
    println!();
    println!("Edit the file to configure your agent, then run:");
    println!("  artemis validate {}", agents_dir().display());
    println!();

    Ok(())
}

fn agents_dir() -> PathBuf {
    if let Ok(dir) = std::env::var("ARTEMIS_AGENTS_DIR") {
        Path::new(&dir).to_path_buf()
    } else if let Ok(home) = std::env::var("HOME") {
        Path::new(&home).join(".artemis").join("agents")
    } else {
        PathBuf::from(".artemis/agents")
    }
}
